/**
 * Pixel theme catalog.
 *
 * Each theme provides:
 *  - id / name        : identity + label
 *  - palette          : 5 swatch colors (for the palette bar)
 *  - colors           : char -> hex map for the 16x16 sprite ('.' = transparent)
 *  - sprite           : 16 rows of 16 chars, hand-authored pixel art
 *
 * The page-level colors (background, borders, text, accent...) live in
 * src/index.css under `body.pixel-theme-<id>` so the WHOLE app recolors.
 * Keep the `id`s here in sync with those CSS classes and the
 * PIXEL_THEMES list in utils/applyGlobalSettings.js.
 */

export const PIXEL_THEMES = [
  {
    id: "ink",
    name: "NOTAION B&W",
    palette: ["#ffffff", "#c0c0c0", "#808080", "#404040", "#000000"],
    accent: "#000000",
    checkFg: "#ffffff",
    screen: "#ffffff",
    colors: { a: "#000000", w: "#ffffff", b: "#808080" },
    sprite: [
      "..aaaaaaaaaaa...",
      "..awwwwwwwaaa...",
      "..awwwwwwwaba...",
      "..awwwwwwwwwa...",
      "..awbbbbbbbwa...",
      "..awwwwwwwwwa...",
      "..awbbbbbbbwa...",
      "..awwwwwwwwwa...",
      "..awbbbbbbbwa...",
      "..awwwwwwwwwa...",
      "..awbbbbbwwwa...",
      "..awwwwwwwwwa...",
      "..aaaaaaaaaaa...",
      "................",
      "................",
      "................",
    ],
  },
  {
    id: "forest",
    name: "DARK FOREST",
    palette: ["#0b1d12", "#1b4d2e", "#2e7d4f", "#4caf6d", "#7fd99a"],
    accent: "#4caf6d",
    screen: "#06120b",
    colors: { c: "#7fd99a", b: "#2e7d4f", a: "#1b4d2e", d: "#3d2914", e: "#5a3a1a" },
    sprite: [
      "................",
      ".......cc.......",
      "......cbbc......",
      "......cbbc......",
      ".....cbbbbc.....",
      "....cbbbbbbc....",
      "....cabbabac....",
      "...cbbbbbbbbc...",
      "..cbbbbbbbbbbc..",
      "..cabbabbababc..",
      ".cbbbbbbbbbbbbc.",
      "cbbbbbbbbbbbbbbc",
      "......deed......",
      "......deed......",
      "......deed......",
      "................",
    ],
  },
  {
    id: "ocean",
    name: "DEEP OCEAN",
    palette: ["#06203f", "#0d47a1", "#1976d2", "#2196f3", "#90caf9"],
    accent: "#2196f3",
    screen: "#03101f",
    colors: { a: "#0d47a1", b: "#2196f3", c: "#90caf9" },
    sprite: [
      ".......a........",
      ".......aa.......",
      "......aba.......",
      "......abba......",
      ".....abbba......",
      ".....abccba.....",
      "....abbccbba....",
      "....abbccbba....",
      "...abbbccbbba...",
      "...abbbbbbbba...",
      "..abbbbbbbbbba..",
      "..abbbbbbbbbba..",
      "...abbbbbbbba...",
      "....abbbbbba....",
      ".....abbbba.....",
      "......aaaa......",
    ],
  },
  {
    id: "lava",
    name: "LAVA CORE",
    palette: ["#2b0a06", "#7a1f0a", "#e53935", "#ff9800", "#ffeb3b"],
    accent: "#ff9800",
    screen: "#0f0402",
    colors: { d: "#e53935", c: "#ff9800", b: "#ffc107", a: "#fff59d" },
    sprite: [
      ".......dd.......",
      "......dddd......",
      "......dddd......",
      ".....ddccdd.....",
      ".....dccccd.....",
      "....dccbbccd....",
      "....dcbbbbcd....",
      "...dcbbaabbcd...",
      "...dcbbaabbcd...",
      "..dccbbaabbccd..",
      "..dccbbbbbbccd..",
      "..dccbbbbbbccd..",
      "...dccbbbbccd...",
      "....dccccccd....",
      ".....dccccd.....",
      "......dddd......",
    ],
  },
  {
    id: "candy",
    name: "CANDY POP",
    palette: ["#5a0b34", "#ad1457", "#ec407a", "#f48fb1", "#ffd6e8"],
    accent: "#ec407a",
    screen: "#1a0512",
    colors: { a: "#ad1457", b: "#ec407a", c: "#f48fb1", d: "#f8bbd0", w: "#ffffff", e: "#bcaaa4" },
    sprite: [
      ".....aaaaaa.....",
      "...aabbbbbbaa...",
      "..abbccccccbba..",
      "..abccddddccba..",
      ".abbcdwwwwdcbba.",
      ".abccdwwwwdccba.",
      ".abcdwwwwwwdcba.",
      ".abcdwwwwwwdcba.",
      ".abccdwwwwdccba.",
      ".abbcdwwwwdcbba.",
      "..abccddddccba..",
      "..abbccccccbba..",
      "...aabbbbbbaa...",
      ".....aeea.......",
      "......ee........",
      "......ee........",
    ],
  },
  {
    id: "void",
    name: "THE VOID",
    palette: ["#000000", "#2a2a2a", "#5a5a5a", "#9a9a9a", "#e8e8e8"],
    accent: "#e8e8e8",
    screen: "#000000",
    colors: { d: "#e8e8e8", c: "#9a9a9a", a: "#000000", b: "#5a5a5a" },
    sprite: [
      "....dddddddd....",
      "...dccccccccd...",
      "..dccccccccccd..",
      "..dccddddddccd..",
      "..dcaaddddaacd..",
      "..dcaaddddaacd..",
      "..dccddddddccd..",
      "..dcccddddcccd..",
      "..dccddaaddccd..",
      "..dccddaaddccd..",
      "...dccddddccd...",
      "....dadadada....",
      "....dadadada....",
      ".....dccccd.....",
      "......dddd......",
      "................",
    ],
  },
  {
    id: "gameboy",
    name: "RETRO GAMEBOY",
    palette: ["#0f380f", "#306230", "#5a7a1a", "#8bac0f", "#9bbc0f"],
    accent: "#9bbc0f",
    screen: "#9bbc0f",
    colors: { e: "#8bac0f", f: "#306230", d: "#9bbc0f", a: "#0f380f", b: "#306230", o: "#0f380f" },
    sprite: [
      "..ffffffffffff..",
      "..feeeeeeeeeef..",
      "..feddddddddef..",
      "..fedaaaaaadef..",
      "..fedaaaaaadef..",
      "..fedaaaaaadef..",
      "..fedaaaaaadef..",
      "..feddddddddef..",
      "..feeeeeeeeeef..",
      "..feeaeeeooeef..",
      "..feaaaeeooeef..",
      "..feeaeeeeeeef..",
      "..feeeeeeeeeef..",
      "..feebbbbbbeef..",
      "..ffffffffffff..",
      "................",
    ],
  },
];

export const PIXEL_THEME_IDS = PIXEL_THEMES.map((t) => t.id);
